/**
 * DRAFT quiz content for local Phase 1 development only, mirroring the
 * DRAFT status of mock-data.ts learning resources — must be reviewed and
 * approved by the project owner before any real seeding.
 */
import type { SkillQuiz } from './types';

export const SKILL_QUIZZES: Record<string, SkillQuiz> = {
  'ce-networking-fundamentals': {
    skillId: 'ce-networking-fundamentals',
    questions: [
      {
        id: 'ce-networking-fundamentals-q1',
        question: 'What AWS resource lets you launch isolated network environments for your resources?',
        options: ['IAM role', 'VPC (Virtual Private Cloud)', 'S3 bucket', 'Lambda function'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-networking-fundamentals-q2',
        question: 'Which component operates at the subnet level and is stateless?',
        options: ['Security group', 'Network ACL', 'Route table', 'Internet gateway'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-networking-fundamentals-q3',
        question:
          'What lets instances in a private subnet reach the internet for outbound updates without being publicly reachable?',
        options: ['NAT gateway', 'Internet gateway', 'VPC peering', 'Elastic IP'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-networking-fundamentals-q4',
        question: 'What determines how traffic is directed between subnets and to the internet?',
        options: ['Route table', 'Security group', 'IAM policy', 'S3 bucket policy'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-networking-fundamentals-q5',
        question: 'What is a CIDR block used for?',
        options: [
          'Defining the IP address range of a VPC or subnet',
          'Encrypting traffic',
          'Managing billing',
          'Scaling compute',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-networking-fundamentals-q6',
        question: 'Which statement about security groups is correct?',
        options: [
          'They are stateful — return traffic is automatically allowed',
          'They are stateless',
          'They only apply to subnets, not instances',
          'They replace route tables',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-networking-fundamentals-q7',
        question: 'What connects two VPCs so resources can communicate privately?',
        options: ['VPC peering', 'NAT gateway', 'Elastic Load Balancer', 'Auto Scaling group'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-networking-fundamentals-q8',
        question: 'Which gateway is required for resources in a public subnet to reach the internet directly?',
        options: ['NAT gateway', 'Internet gateway', 'Transit gateway', 'VPN gateway'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-networking-fundamentals-q9',
        question: 'What is the smallest unit of IP addressing you typically assign within a VPC?',
        options: ['Region', 'Availability Zone', 'Subnet', 'Edge location'],
        correctOptionIndex: 2,
      },
      {
        id: 'ce-networking-fundamentals-q10',
        question: 'Why might you split a VPC into multiple subnets across Availability Zones?',
        options: [
          'To reduce cost only',
          'To increase fault tolerance and availability',
          'To disable security groups',
          'It has no real benefit',
        ],
        correctOptionIndex: 1,
      },
    ],
  },
  'ce-iam': {
    skillId: 'ce-iam',
    questions: [
      {
        id: 'ce-iam-q1',
        question: 'What is the recommended security practice when granting permissions?',
        options: [
          'Grant full admin access for simplicity',
          'Least privilege — only the permissions needed',
          'Share root credentials across the team',
          'Disable all permission checks',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iam-q2',
        question: 'In IAM, what attaches permissions to a user, group, or role?',
        options: ['A security group', 'A policy', 'A route table', 'A subnet'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iam-q3',
        question: 'What is an IAM role typically used for?',
        options: [
          'A fixed set of long-term credentials for a person',
          'Temporary credentials assumable by users or services',
          'A billing configuration',
          'A network firewall rule',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iam-q4',
        question: 'What is Multi-Factor Authentication (MFA) used for?',
        options: [
          'Adding an extra layer of identity verification beyond a password',
          'Encrypting S3 buckets',
          'Routing network traffic',
          'Load balancing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iam-q5',
        question: 'What does an IAM policy document typically define?',
        options: [
          'Allowed/denied actions on specific resources',
          'Server CPU allocation',
          'Database schema',
          'DNS records',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iam-q6',
        question: "What is the risk of using the root account for daily tasks?",
        options: [
          "No risk, it's the most secure",
          'It has unrestricted access and its compromise is catastrophic',
          "It's required for all operations",
          "It's the same as any IAM user",
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iam-q7',
        question: 'What is a good practice for granting temporary elevated access?',
        options: [
          'Permanently grant admin access',
          'Use short-lived assumed roles with defined permissions',
          'Share credentials over email',
          'Disable logging',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iam-q8',
        question: 'Which IAM feature groups permissions for easier management across multiple users?',
        options: ['IAM groups', 'Security groups', 'Route tables', 'Load balancers'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iam-q9',
        question: 'What does "principal" refer to in an IAM policy?',
        options: [
          'The entity (user, role, or service) the policy applies to',
          'The AWS region',
          'The resource ARN only',
          'The billing account',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iam-q10',
        question:
          'Why use resource-based policies (e.g., on an S3 bucket) instead of only identity-based policies?',
        options: [
          'To grant cross-account or fine-grained access directly on the resource',
          'They are required for every action',
          'They replace all IAM roles',
          'They only work for EC2',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'ce-compute': {
    skillId: 'ce-compute',
    questions: [
      {
        id: 'ce-compute-q1',
        question: 'Which compute option lets you run code without provisioning or managing servers?',
        options: ['EC2 reserved instance', 'AWS Lambda', 'On-premises VM', 'Dedicated host'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-compute-q2',
        question: 'What is a key trade-off of serverless compute compared to always-on EC2 instances?',
        options: [
          'Serverless requires manual OS patching',
          'Serverless has cold-start latency but scales automatically',
          'EC2 cannot scale at all',
          'There is no cost difference between the two',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-compute-q3',
        question: 'What is EC2 primarily used for?',
        options: [
          'Serverless functions only',
          'Resizable virtual server instances',
          'Static file hosting only',
          'DNS management',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-compute-q4',
        question: 'What is "auto scaling" used for?',
        options: [
          'Automatically adjusting compute capacity based on demand',
          'Automatically deleting unused IAM users',
          'Automatically encrypting data',
          'Automatically routing DNS',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-compute-q5',
        question: 'What is a container orchestrator like ECS or Kubernetes primarily used to manage?',
        options: [
          'Deploying and scaling containerized workloads',
          'Managing DNS zones',
          'Configuring VPNs',
          'Billing alerts',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-compute-q6',
        question: "What's a benefit of choosing a managed compute service over self-managed servers?",
        options: [
          'Less operational overhead (patching, scaling handled for you)',
          'Complete control over the kernel',
          'No cost',
          'Guaranteed zero latency',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-compute-q7',
        question: 'What typically triggers an AWS Lambda function?',
        options: [
          'Only manual invocation via console',
          'Events such as HTTP requests, file uploads, or queue messages',
          'Only scheduled cron jobs',
          'It cannot be triggered',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-compute-q8',
        question: 'What is a "cold start" in serverless computing?',
        options: [
          'The delay when a function is invoked after being idle and needs to initialize',
          'A database backup process',
          'A network timeout error',
          'A billing cycle reset',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-compute-q9',
        question:
          'Which compute purchasing option offers the largest discount for predictable, steady-state usage?',
        options: ['On-demand instances', 'Reserved instances / savings plans', 'Spot instances only', 'Free tier'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-compute-q10',
        question: 'What is a Spot Instance best suited for?',
        options: [
          'Critical always-on production workloads',
          'Fault-tolerant, interruptible workloads at a lower price',
          'Long-term reserved capacity',
          'Real-time trading systems',
        ],
        correctOptionIndex: 1,
      },
    ],
  },
  'ce-storage': {
    skillId: 'ce-storage',
    questions: [
      {
        id: 'ce-storage-q1',
        question: 'Which AWS service is object storage ideal for static assets and backups?',
        options: ['DynamoDB', 'EBS', 'S3', 'RDS'],
        correctOptionIndex: 2,
      },
      {
        id: 'ce-storage-q2',
        question: 'What kind of database is DynamoDB?',
        options: [
          'Relational SQL database',
          'Key-value / NoSQL database',
          'Graph database only',
          'In-memory cache only',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-storage-q3',
        question: 'What S3 storage class is designed for infrequently accessed data at a lower cost?',
        options: ['S3 Standard', 'S3 Standard-IA (Infrequent Access)', 'S3 multi-region', 'S3 Snowball'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-storage-q4',
        question: 'What does EBS provide?',
        options: [
          'Object storage for the internet',
          'Block storage volumes attached to EC2 instances',
          'A managed relational database',
          'A content delivery network',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-storage-q5',
        question: 'What is a "lifecycle policy" in S3 used for?',
        options: [
          'Automatically transitioning or expiring objects over time',
          'Encrypting IAM users',
          'Configuring load balancers',
          'Managing VPC routing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-storage-q6',
        question: 'What consistency model does DynamoDB support for reads?',
        options: [
          'Only eventual consistency',
          'Both eventually consistent and strongly consistent reads',
          'Only strong consistency',
          'No consistency guarantees',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-storage-q7',
        question: 'What is versioning in S3 used for?',
        options: [
          'Preserving multiple variants of an object to protect against accidental deletion or overwrite',
          'Speeding up uploads',
          'Encrypting data at rest only',
          'Reducing storage cost',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-storage-q8',
        question: 'Which AWS service provides a fully managed relational database?',
        options: ['DynamoDB', 'RDS', 'S3', 'CloudFront'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-storage-q9',
        question: 'What is "data durability" primarily about?',
        options: [
          'How fast data can be read',
          'The probability data will not be lost over time',
          'How cheap the storage is',
          'How the data is encrypted',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-storage-q10',
        question: 'What is a common reason to choose a NoSQL database like DynamoDB over a relational database?',
        options: [
          'Need for complex multi-table JOIN queries',
          'Need for flexible schema and massive horizontal scale',
          'Need for strict ACID transactions across many tables',
          'Need for a smaller dataset only',
        ],
        correctOptionIndex: 1,
      },
    ],
  },
  'ce-iac': {
    skillId: 'ce-iac',
    questions: [
      {
        id: 'ce-iac-q1',
        question: 'What does "Infrastructure as Code" primarily let teams do?',
        options: [
          'Manually click through a cloud console for every change',
          'Define and version infrastructure using declarative config files',
          'Avoid using version control',
          'Replace all application code',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iac-q2',
        question: 'Which tool is a widely used, cloud-agnostic Infrastructure as Code tool?',
        options: ['Terraform', 'Photoshop', 'Excel', 'A Jenkinsfile alone'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iac-q3',
        question: 'What is "declarative" configuration in IaC?',
        options: [
          'You specify the desired end state and the tool figures out how to get there',
          'You write step-by-step imperative scripts only',
          'It requires no configuration file',
          'It only works with one cloud provider',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iac-q4',
        question: 'What is a Terraform "provider"?',
        options: [
          "A plugin that lets Terraform interact with a specific platform's API (e.g., AWS)",
          'A type of virtual machine',
          'A billing report',
          'A security group',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iac-q5',
        question: 'Why is code review valuable for infrastructure changes, just like application code?',
        options: [
          'It is not valuable, infra changes are always safe',
          'It helps catch mistakes before they affect live infrastructure',
          'It is only for compliance paperwork',
          'It slows down deployment for no benefit',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iac-q6',
        question: 'What does "idempotent" mean when applying IaC?',
        options: [
          'Applying the same configuration repeatedly produces the same result without unintended side effects',
          'It can only be applied once ever',
          'It always destroys and recreates everything',
          'It ignores existing resources',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iac-q7',
        question: 'What is a common risk of manually editing resources that are also managed by IaC?',
        options: [
          'No risk at all',
          'Configuration drift between the real infrastructure and the code',
          'Automatic self-healing',
          'Faster deployments',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iac-q8',
        question: 'What do modules in Terraform help with?',
        options: [
          'Reusing and organizing infrastructure code',
          'Only formatting code style',
          'Replacing all variables',
          'Managing billing alerts',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-iac-q9',
        question: 'What is a common first step before applying Terraform changes to production?',
        options: [
          'Skip review and apply directly',
          'Run a plan to preview changes',
          'Delete the state file',
          'Disable version control',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-iac-q10',
        question: 'Why store Terraform state remotely (e.g., in S3) for a team?',
        options: [
          'To enable shared, locked access to a consistent view of infrastructure state',
          'It is required for the code to compile',
          'It replaces the need for version control',
          'It encrypts application secrets automatically',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'ce-linux-fundamentals': {
    skillId: 'ce-linux-fundamentals',
    questions: [
      {
        id: 'ce-linux-fundamentals-q1',
        question: 'Which command lists the contents of a directory in Linux?',
        options: ['cd', 'ls', 'rm', 'grep'],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-linux-fundamentals-q2',
        question: 'What does the `chmod` command change on a file?',
        options: ['File permissions', 'File contents', 'File name', "File owner's email"],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-linux-fundamentals-q3',
        question: 'What does `grep` do?',
        options: ['Searches text using patterns', 'Changes file permissions', 'Displays disk usage', 'Compiles a program'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-linux-fundamentals-q4',
        question: 'What is the purpose of the `sudo` command?',
        options: [
          'Run a command with elevated (superuser) privileges',
          'Schedule a recurring job',
          'Compress a file',
          'Show network connections',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-linux-fundamentals-q5',
        question: 'What does the `ps` command show?',
        options: ['Running processes', 'File permissions', 'Disk partitions', 'Network routes'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-linux-fundamentals-q6',
        question: 'What is a Linux "pipe" (`|`) used for?',
        options: [
          'Sending the output of one command as input to another',
          'Deleting a file',
          'Renaming a directory',
          'Encrypting a file',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-linux-fundamentals-q7',
        question: 'What does the `/etc` directory typically contain?',
        options: [
          'User home directories',
          'System-wide configuration files',
          'Temporary files only',
          'Compiled binaries only',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-linux-fundamentals-q8',
        question: 'Which command shows current disk space usage?',
        options: ['df', 'cd', 'mv', 'cat'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-linux-fundamentals-q9',
        question: "What is a shell script's shebang line for?",
        options: [
          'A comment header',
          'Specifying which interpreter runs the script',
          'A version tag',
          'A security signature',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-linux-fundamentals-q10',
        question: 'What does `chown` change on a file?',
        options: ['File permissions', 'File owner and group', 'File contents', 'File name'],
        correctOptionIndex: 1,
      },
    ],
  },
  'ce-cost-optimization': {
    skillId: 'ce-cost-optimization',
    questions: [
      {
        id: 'ce-cost-optimization-q1',
        question: 'What is "rightsizing" in the context of cloud cost optimization?',
        options: [
          'Choosing the largest instance type available',
          'Matching resource size to actual workload needs to avoid overpaying',
          'Deleting all resources',
          'Ignoring usage reports',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-cost-optimization-q2',
        question: 'What AWS feature helps you get notified before spending exceeds a threshold?',
        options: ['Budgets and alerts', 'Security groups', 'VPC peering', 'IAM roles'],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-cost-optimization-q3',
        question: 'What is a Reserved Instance / Savings Plan primarily used for?',
        options: [
          'Reducing cost for predictable, steady-state usage by committing upfront',
          'Guaranteeing unlimited free usage',
          'Increasing latency',
          'Avoiding all monitoring',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-cost-optimization-q4',
        question: 'What does a "Cost and Usage Report" help you do?',
        options: [
          'Analyze detailed spending patterns across services',
          'Configure security groups',
          'Manage DNS',
          'Deploy containers',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-cost-optimization-q5',
        question:
          'Why might unused or idle resources (like unattached EBS volumes) increase cost unnecessarily?',
        options: [
          'They are always free',
          'They continue to incur charges even when not actively used',
          'They automatically delete themselves',
          'They reduce your bill',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-cost-optimization-q6',
        question: 'What is a tagging strategy useful for in cost management?',
        options: [
          'Attributing costs to teams, projects, or environments for visibility',
          'Encrypting resources',
          'Routing network traffic',
          'Replacing IAM policies',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-cost-optimization-q7',
        question: 'What can Spot Instances offer for cost optimization?',
        options: [
          'Guaranteed availability at standard price',
          'Significant discounts for interruptible workloads',
          'Free unlimited compute',
          'They are only used for storage',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'ce-cost-optimization-q8',
        question:
          'What does Savings Plans flexibility typically allow compared to standard Reserved Instances?',
        options: [
          'More flexibility across instance families/regions in exchange for a spend commitment',
          'No commitment at all',
          'It only works for storage',
          'Requires paying full on-demand price',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-cost-optimization-q9',
        question: 'Why review underutilized resources regularly?',
        options: [
          'To identify opportunities to downsize or terminate and reduce waste',
          'It is not useful',
          'It increases the AWS bill intentionally',
          'It replaces security audits',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'ce-cost-optimization-q10',
        question: 'What AWS tool visualizes and forecasts your spending trends?',
        options: ['Cost Explorer', 'Security Hub', 'CloudTrail', 'Route 53'],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-cicd': {
    skillId: 'de-cicd',
    questions: [
      {
        id: 'de-cicd-q1',
        question: 'What does CI (Continuous Integration) primarily focus on?',
        options: [
          'Manually deploying once a year',
          'Frequently merging and automatically testing code changes',
          'Writing documentation only',
          'Disabling automated tests',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-cicd-q2',
        question: 'In a typical CI/CD pipeline, what usually happens right after code is merged?',
        options: [
          'Nothing, until someone remembers',
          'Automated build and test steps run',
          'The production database is deleted',
          'The repository is archived',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-cicd-q3',
        question: 'What does CD typically stand for in a CI/CD pipeline (deployment sense)?',
        options: ['Continuous Deployment/Delivery', 'Central Database', 'Code Duplication', 'Container Distribution'],
        correctOptionIndex: 0,
      },
      {
        id: 'de-cicd-q4',
        question: 'What is a "pipeline stage" typically used for?',
        options: [
          'Grouping related steps like build, test, or deploy',
          'Storing secrets in plaintext',
          'Replacing version control',
          'Encrypting the repository',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-cicd-q5',
        question: 'Why run automated tests in a pipeline before deployment?',
        options: [
          'To catch regressions before they reach production',
          'To slow down releases for no reason',
          'Tests are optional and rarely useful',
          'To replace code review entirely',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-cicd-q6',
        question: 'What is a "rollback" in a deployment pipeline?',
        options: [
          'Reverting to a previous, known-good version after a failed release',
          'Permanently deleting the application',
          'Merging two branches',
          'Scaling up servers',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-cicd-q7',
        question: 'What is the benefit of running pipeline steps in parallel where possible?',
        options: [
          'Faster feedback by reducing overall pipeline duration',
          'It always reduces test coverage',
          'It removes the need for tests',
          'It increases flakiness intentionally',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-cicd-q8',
        question: 'What is a "build artifact"?',
        options: [
          'The packaged output of a build step (e.g., a binary or container image) used in later stages',
          'A test report only',
          'A security vulnerability',
          'A git commit message',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-cicd-q9',
        question: 'What does "trunk-based development" encourage?',
        options: [
          'Long-lived feature branches that merge yearly',
          'Frequent, small merges to a shared main branch',
          'Avoiding automated testing',
          'Manual deployments only',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-cicd-q10',
        question: 'Why use environment-specific configuration (e.g., staging vs. production) in a pipeline?',
        options: [
          'To safely test changes before they affect real users',
          'It is not necessary',
          'To make pipelines slower',
          'To bypass security review',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-containers': {
    skillId: 'de-containers',
    questions: [
      {
        id: 'de-containers-q1',
        question: 'What does a Dockerfile define?',
        options: [
          'A network firewall rule',
          'The steps to build a container image',
          'A Kubernetes cluster',
          'A database schema',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-containers-q2',
        question: 'What is the main benefit of containers over traditional VMs?',
        options: [
          'Containers are heavier and slower',
          'Containers share the host OS kernel, making them lightweight and fast to start',
          'Containers require their own physical hardware',
          'Containers cannot be version controlled',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-containers-q3',
        question: 'What is a container "image registry" (e.g., Docker Hub) used for?',
        options: [
          'Storing and distributing container images',
          'Compiling source code',
          'Managing DNS records',
          'Monitoring CPU usage',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-containers-q4',
        question: 'What does the `docker run` command do?',
        options: [
          'Builds an image from a Dockerfile',
          'Starts a new container from an image',
          'Deletes a container',
          'Lists running processes on the host',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-containers-q5',
        question: 'Why are containers considered more portable than traditional deployments?',
        options: [
          'They package the app and its dependencies together to run consistently across environments',
          'They require a specific physical server',
          'They only run on one operating system version',
          'They cannot be moved once started',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-containers-q6',
        question: 'What is a "volume" in Docker used for?',
        options: [
          "Persisting data outside a container's writable layer",
          'Increasing CPU allocation',
          'Encrypting network traffic',
          'Load balancing requests',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-containers-q7',
        question: 'What does `docker-compose` (or a Compose file) help you do?',
        options: [
          'Define and run multi-container applications together',
          'Compile a single binary',
          'Manage IAM permissions',
          'Replace Kubernetes entirely',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-containers-q8',
        question: 'Why keep container images small (multi-stage builds, minimal base images)?',
        options: [
          'Faster pulls/starts and a smaller attack surface',
          'It has no benefit',
          'It always breaks the app',
          'It is required by law',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-containers-q9',
        question: 'What is the difference between a container and an image?',
        options: [
          'An image is a running instance of a container',
          'A container is a running instance created from an image',
          'They are exactly the same thing',
          'An image only exists on Kubernetes',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-containers-q10',
        question: 'What Linux kernel features do containers rely on for isolation?',
        options: ['Namespaces and cgroups', 'Only encryption keys', 'DNS servers', 'Virtual GPUs'],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-monitoring': {
    skillId: 'de-monitoring',
    questions: [
      {
        id: 'de-monitoring-q1',
        question: 'What are three common pillars of observability?',
        options: ['Logs, metrics, traces', 'Colors, fonts, icons', 'CPU, RAM, disk only', 'Passwords, tokens, keys'],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q2',
        question: 'What is the purpose of an alarm/alert in a monitoring system?',
        options: [
          'To automatically notify the team when a metric crosses a threshold',
          'To permanently delete logs',
          'To slow down the application',
          'To replace testing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q3',
        question: 'What is a "dashboard" in an observability tool typically used for?',
        options: [
          'Visualizing key metrics and system health at a glance',
          'Storing raw log files only',
          'Managing IAM permissions',
          'Compiling application code',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q4',
        question: 'What is "log aggregation"?',
        options: [
          'Collecting logs from multiple sources into a central place for analysis',
          'Deleting old logs automatically',
          'Encrypting network traffic',
          'Load balancing requests',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q5',
        question: 'What does a "trace" typically represent in distributed tracing?',
        options: [
          'The path and timing of a request as it moves through multiple services',
          'A single log line',
          'A CPU metric',
          'A security policy',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q6',
        question: 'What is the purpose of setting a meaningful alert threshold?',
        options: [
          'To reduce noise and alert only on actionable issues',
          'To alert on every possible metric change',
          'To disable monitoring entirely',
          'To increase false positives intentionally',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q7',
        question: 'What is "on-call" rotation used for in incident response?',
        options: [
          'Ensuring someone is responsible for responding to alerts at all times',
          'Assigning permanent ownership of all code',
          'Replacing monitoring tools',
          'Scheduling vacations',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q8',
        question: 'Why is it useful to correlate logs, metrics, and traces together?',
        options: [
          'To get a fuller picture when diagnosing an issue',
          'It is not useful',
          'It only helps with billing',
          'It replaces the need for testing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q9',
        question: 'What is a Service Level Objective (SLO)?',
        options: [
          'A target level of reliability or performance a service aims to meet',
          'A type of database index',
          'A network firewall rule',
          'A billing tier',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-monitoring-q10',
        question: 'What is the purpose of a post-incident review (postmortem)?',
        options: [
          'To understand root cause and prevent recurrence without blaming individuals',
          'To assign punishment',
          'To hide the issue from stakeholders',
          'To skip fixing the root cause',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-iac': {
    skillId: 'de-iac',
    questions: [
      {
        id: 'de-iac-q1',
        question: 'What is the main advantage of managing infrastructure with code instead of manual steps?',
        options: [
          'Reproducibility and version control',
          'It requires no documentation',
          'It prevents all outages automatically',
          'It eliminates the need for testing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q2',
        question: "Which Terraform concept tracks the current state of managed infrastructure?",
        options: ['State file', 'Dockerfile', 'YAML pipeline', 'IAM policy'],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q3',
        question: 'What is "declarative" configuration in IaC?',
        options: [
          'You specify the desired end state and the tool figures out how to get there',
          'You write step-by-step imperative scripts only',
          'It requires no configuration file',
          'It only works with one cloud provider',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q4',
        question: 'What is a Terraform "provider"?',
        options: [
          "A plugin that lets Terraform interact with a specific platform's API (e.g., AWS)",
          'A type of virtual machine',
          'A billing report',
          'A security group',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q5',
        question: 'What does "idempotent" mean when applying IaC?',
        options: [
          'Applying the same configuration repeatedly produces the same result without unintended side effects',
          'It can only be applied once ever',
          'It always destroys and recreates everything',
          'It ignores existing resources',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q6',
        question: 'What is a common risk of manually editing resources that are also managed by IaC?',
        options: [
          'No risk at all',
          'Configuration drift between the real infrastructure and the code',
          'Automatic self-healing',
          'Faster deployments',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-iac-q7',
        question: 'What do modules in Terraform help with?',
        options: [
          'Reusing and organizing infrastructure code',
          'Only formatting code style',
          'Replacing all variables',
          'Managing billing alerts',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q8',
        question: 'What is a common first step before applying Terraform changes to production?',
        options: [
          'Skip review and apply directly',
          'Run a plan to preview changes',
          'Delete the state file',
          'Disable version control',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-iac-q9',
        question: 'Why store Terraform state remotely (e.g., in S3) for a team?',
        options: [
          'To enable shared, locked access to a consistent view of infrastructure state',
          'It is required for the code to compile',
          'It replaces the need for version control',
          'It encrypts application secrets automatically',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-iac-q10',
        question:
          'What is a common way to manage different environments (dev/staging/prod) with the same Terraform code?',
        options: [
          'Using workspaces or separate variable files per environment',
          'Copy-pasting code manually for each environment',
          'Only using one shared environment',
          'Avoiding IaC for non-production',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-security-scanning': {
    skillId: 'de-security-scanning',
    questions: [
      {
        id: 'de-security-scanning-q1',
        question: 'What does dependency scanning in a CI pipeline check for?',
        options: [
          'Known vulnerabilities in third-party libraries',
          'Code formatting only',
          'Variable naming conventions',
          'Compiler warnings only',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q2',
        question: 'What is "shift-left security"?',
        options: [
          'Moving security testing later, after production release',
          'Catching security issues earlier in the development process',
          'Removing all security checks',
          'Only checking security once a year',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-security-scanning-q3',
        question: 'What is "secret scanning" in a CI pipeline designed to catch?',
        options: [
          'Accidentally committed credentials or API keys in source code',
          'Slow test execution',
          'Unused variables',
          'Formatting issues',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q4',
        question: 'What is a Static Application Security Testing (SAST) tool used for?',
        options: [
          'Analyzing source code for vulnerabilities without executing it',
          'Only testing network latency',
          'Managing billing',
          'Deploying infrastructure',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q5',
        question: 'What is a Software Bill of Materials (SBOM)?',
        options: [
          'An inventory of all components/dependencies in a piece of software',
          'A pricing invoice',
          'A network diagram',
          'A user manual',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q6',
        question: 'Why block a pipeline on a critical vulnerability finding?',
        options: [
          'To prevent shipping known, high-risk security issues to production',
          'It is unnecessary friction',
          'It has no security benefit',
          'It only slows down unrelated teams',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q7',
        question: 'What does Dynamic Application Security Testing (DAST) do differently from SAST?',
        options: [
          'Tests the running application for vulnerabilities rather than static source code',
          'It only checks code formatting',
          'It replaces all manual testing',
          'It only runs once a year',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q8',
        question: 'What is a common remediation for a vulnerable dependency?',
        options: [
          'Upgrade to a patched version or apply a mitigation',
          'Ignore it permanently',
          'Delete all dependencies',
          'Disable the scanner',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q9',
        question: 'Why integrate security scanning early rather than only before release?',
        options: [
          'Issues are cheaper and easier to fix when caught early',
          'It is more expensive to fix early',
          'It has no timing impact',
          'It only matters after release',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-security-scanning-q10',
        question: 'What is the purpose of a vulnerability severity rating (e.g., a CVSS score)?',
        options: [
          'To help prioritize which issues to fix first',
          'To determine team salaries',
          'To set the cloud region',
          'To configure DNS',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-linux-scripting': {
    skillId: 'de-linux-scripting',
    questions: [
      {
        id: 'de-linux-scripting-q1',
        question: 'What is the shebang line `#!/bin/bash` used for?',
        options: [
          'Adding a comment ignored by the shell',
          'Specifying which interpreter should run the script',
          'Declaring a variable',
          'Importing a library',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'de-linux-scripting-q2',
        question: 'Which bash construct lets you repeat a command for each item in a list?',
        options: ['if/else', 'for loop', 'chmod', 'grep'],
        correctOptionIndex: 1,
      },
      {
        id: 'de-linux-scripting-q3',
        question: 'What do `$1`, `$2` refer to in a bash script?',
        options: [
          'Positional arguments passed to the script',
          'Environment variables only',
          'File permissions',
          'Process IDs',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q4',
        question: 'What does `chmod +x script.sh` do?',
        options: ['Makes the script executable', 'Deletes the script', 'Compiles the script', 'Encrypts the script'],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q5',
        question: 'What is the purpose of `cron` in Linux?',
        options: [
          'Scheduling recurring tasks or jobs',
          'Managing IAM permissions',
          'Compiling code',
          'Monitoring CPU temperature',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q6',
        question: 'What does `if [ -f file.txt ]; then ... fi` check for?',
        options: [
          'Whether a file exists',
          'Whether a user is logged in',
          'Whether the network is up',
          'Whether a process is running',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q7',
        question: 'What is the purpose of exit codes in shell scripts?',
        options: [
          'Indicating success or failure of a command for automation and error handling',
          'Formatting output text',
          'Encrypting output',
          'Naming variables',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q8',
        question: 'What does redirecting output with `>>` do compared to `>`?',
        options: [
          'Appends to a file instead of overwriting it',
          'Deletes the file',
          'Pipes to another command',
          'Compresses output',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q9',
        question: 'What is a common use of `awk` or `sed` in scripting?',
        options: [
          'Text processing and transformation',
          'Managing network routes',
          'Building container images',
          'Managing IAM roles',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-linux-scripting-q10',
        question: 'Why add error handling (like `set -e`) to bash scripts used in automation?',
        options: [
          'To stop the script on the first error rather than continuing silently',
          'To make the script run slower',
          'To disable logging',
          'To skip all validation',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'de-kubernetes': {
    skillId: 'de-kubernetes',
    questions: [
      {
        id: 'de-kubernetes-q1',
        question: 'What Kubernetes object manages a set of identical, replicated pods?',
        options: ['ConfigMap', 'Deployment', 'Secret', 'Namespace only'],
        correctOptionIndex: 1,
      },
      {
        id: 'de-kubernetes-q2',
        question: 'What does a Kubernetes Service provide?',
        options: [
          'A stable network endpoint to reach a set of pods',
          'A way to build container images',
          'A billing dashboard',
          'A Linux kernel patch',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q3',
        question: 'What is a Kubernetes "Pod"?',
        options: [
          'The smallest deployable unit, typically wrapping one or more containers',
          'A physical server',
          'A billing unit',
          'A DNS record',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q4',
        question: 'What does a "Namespace" in Kubernetes provide?',
        options: [
          'A way to logically isolate and organize resources within a cluster',
          'A network firewall',
          'A container image',
          'A billing report',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q5',
        question: 'What is a "ConfigMap" used for?',
        options: [
          'Storing non-sensitive configuration data separately from application code',
          'Storing encrypted secrets only',
          'Scheduling pods',
          'Load balancing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q6',
        question: 'What is the purpose of a Kubernetes "Secret"?',
        options: [
          'Storing sensitive data like passwords or tokens',
          'Storing container images',
          'Managing node scaling',
          'Defining network policies',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q7',
        question: 'What does horizontal pod autoscaling do?',
        options: [
          'Automatically adjusts the number of pod replicas based on load',
          'Automatically upgrades the Kubernetes version',
          'Automatically deletes namespaces',
          'Automatically creates new clusters',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q8',
        question: 'What is a "node" in a Kubernetes cluster?',
        options: [
          'A worker machine (VM or physical) that runs pods',
          'A single container',
          'A DNS entry',
          'A billing account',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q9',
        question: 'What component schedules pods onto nodes in Kubernetes?',
        options: ['The scheduler', 'The Dockerfile', 'The Ingress controller', 'The ConfigMap'],
        correctOptionIndex: 0,
      },
      {
        id: 'de-kubernetes-q10',
        question: 'What is an "Ingress" resource used for?',
        options: [
          'Managing external HTTP/S access and routing to services in the cluster',
          'Storing secrets',
          'Scaling nodes',
          'Scheduling cron jobs',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-core-python': {
    skillId: 'pd-core-python',
    questions: [
      {
        id: 'pd-core-python-q1',
        question: 'Which of these is a mutable data structure in Python?',
        options: ['tuple', 'list', 'str', 'frozenset'],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-core-python-q2',
        question: 'What keyword is used to define a function in Python?',
        options: ['func', 'def', 'function', 'lambda only'],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-core-python-q3',
        question: 'What does a Python list comprehension do?',
        options: [
          'Creates a new list concisely from an iterable',
          'Deletes items from a list',
          'Sorts a dictionary',
          'Compiles the script',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q4',
        question: 'What is the difference between a list and a tuple?',
        options: [
          'Lists are mutable, tuples are immutable',
          'Tuples are mutable, lists are immutable',
          'They are identical',
          "Lists can't hold numbers",
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q5',
        question: 'What does `self` refer to inside a Python class method?',
        options: ['The instance the method is called on', 'The class itself', 'A global variable', 'The module name'],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q6',
        question: 'What is a Python dictionary primarily used for?',
        options: [
          'Storing key-value pairs',
          'Storing only unique unordered numbers',
          'Compiling code',
          'Managing file permissions',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q7',
        question: 'What does the `len()` function return?',
        options: [
          'The number of items in a collection or characters in a string',
          'The type of a variable',
          'The memory address',
          'The last item',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q8',
        question: 'What is exception handling (`try`/`except`) used for?',
        options: [
          'Gracefully handling errors instead of crashing the program',
          'Formatting code',
          'Importing modules',
          'Managing memory manually',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q9',
        question: 'What does `==` check in Python, compared to `is`?',
        options: [
          'Value equality, whereas `is` checks identity',
          'Identity, whereas `is` checks value',
          'They are exactly the same',
          'Neither compares anything',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-core-python-q10',
        question: 'What is a Python module?',
        options: [
          'A file containing Python code that can be imported and reused',
          'A type of loop',
          'A database table',
          'A network socket',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-testing': {
    skillId: 'pd-testing',
    questions: [
      {
        id: 'pd-testing-q1',
        question: 'In pytest, what is a "fixture" used for?',
        options: [
          'Formatting code style',
          'Providing reusable setup/teardown logic for tests',
          'Compiling the code',
          'Deploying to production',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-testing-q2',
        question: 'What is the purpose of mocking in unit tests?',
        options: [
          'To replace real dependencies with controlled fake behavior',
          'To make tests run slower',
          'To test the UI visually',
          'To delete test data permanently',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q3',
        question: 'What is "test coverage"?',
        options: [
          'A measure of how much of the code is exercised by tests',
          'The speed of test execution',
          'The number of developers on a team',
          'The number of bugs found',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q4',
        question: 'What is the difference between a unit test and an integration test?',
        options: [
          'Unit tests check individual components in isolation; integration tests check how components work together',
          'They are the same thing',
          'Integration tests only run in production',
          'Unit tests require a live database',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q5',
        question: 'What does `assert` do in a test?',
        options: [
          'Checks that a condition is true and fails the test if not',
          'Prints a log message',
          'Starts the test runner',
          'Formats output',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q6',
        question: 'Why should tests be independent of each other?',
        options: [
          'So failures are easy to isolate and tests can run in any order',
          'So they always run slower',
          'So only one test can ever run',
          'It is not important',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q7',
        question: 'What is a "regression test" meant to catch?',
        options: [
          'Previously working functionality that broke due to a new change',
          'New feature requests',
          'UI color choices',
          'Server uptime',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q8',
        question: 'What is Test-Driven Development (TDD)?',
        options: [
          'Writing a failing test before writing the code to make it pass',
          'Writing tests only after release',
          'Skipping tests entirely',
          'Testing only in production',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q9',
        question: 'What does a code coverage report typically NOT guarantee?',
        options: [
          'That the tested code is bug-free even at 100% coverage',
          'The number of lines in the project',
          'The programming language used',
          'The test framework name',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-testing-q10',
        question: 'Why use continuous integration to run tests automatically?',
        options: [
          'To catch failures immediately on every change rather than relying on manual runs',
          'To avoid writing tests altogether',
          'To slow down development',
          'To replace code review',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-fastapi': {
    skillId: 'pd-fastapi',
    questions: [
      {
        id: 'pd-fastapi-q1',
        question: 'What library does FastAPI use for data validation and settings management?',
        options: ['NumPy', 'Pydantic', 'Flask', 'Django ORM'],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-fastapi-q2',
        question: 'What does FastAPI automatically generate for your API based on your code?',
        options: [
          'Nothing extra',
          'Interactive OpenAPI/Swagger documentation',
          'A mobile app',
          'A SQL database schema only',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-fastapi-q3',
        question: 'What HTTP method is typically used to create a new resource in a REST API?',
        options: ['GET', 'POST', 'DELETE', 'OPTIONS'],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-fastapi-q4',
        question: 'What does a path parameter in FastAPI (e.g., `/items/{item_id}`) represent?',
        options: [
          'A dynamic value extracted from the URL path',
          'A query string value',
          'A request header',
          'A cookie',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-fastapi-q5',
        question: 'What is dependency injection in FastAPI used for (e.g., `Depends`)?',
        options: [
          'Reusing logic like authentication or database sessions across routes',
          'Formatting responses only',
          'Compiling the app',
          'Managing DNS',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-fastapi-q6',
        question: 'What status code typically indicates a successful resource creation?',
        options: ['200', '201', '404', '500'],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-fastapi-q7',
        question: 'What is the purpose of response models in FastAPI?',
        options: [
          'Defining and validating the shape of data returned by an endpoint',
          'Encrypting the response',
          'Rate limiting requests',
          'Load balancing',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-fastapi-q8',
        question: 'What does asynchronous route handling (`async def`) allow FastAPI to do efficiently?',
        options: [
          'Handle many concurrent I/O-bound requests without blocking',
          'Run code faster than any other framework always',
          'Avoid needing a web server',
          'Skip input validation',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-fastapi-q9',
        question: 'What is middleware used for in a web framework like FastAPI?',
        options: [
          'Running shared logic (like logging or auth) before/after each request',
          'Storing the database schema',
          'Compiling routes',
          'Managing CSS',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-fastapi-q10',
        question: 'What does a 422 status code typically indicate in FastAPI?',
        options: ['Request validation failed', 'The server crashed', 'The resource was deleted', 'Authentication succeeded'],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-databases': {
    skillId: 'pd-databases',
    questions: [
      {
        id: 'pd-databases-q1',
        question:
          'What is a defining characteristic of NoSQL databases like DynamoDB compared to relational databases?',
        options: [
          'They always require a fixed schema',
          'They often favor flexible schemas and horizontal scalability',
          'They cannot store JSON-like documents',
          'They only run on a single machine',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-databases-q2',
        question: 'What is "data modeling" primarily concerned with?',
        options: [
          'Choosing font styles for a report',
          'Structuring how data is stored and accessed to meet application needs',
          'Writing marketing copy',
          'Configuring network firewalls',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-databases-q3',
        question: 'What is a primary key used for in a database table?',
        options: [
          'Uniquely identifying each record',
          'Formatting the table',
          'Encrypting data',
          'Sorting columns alphabetically',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q4',
        question: 'What is a foreign key used for in a relational database?',
        options: [
          'Linking a record to a related record in another table',
          'Encrypting a column',
          'Indexing text search',
          'Compressing storage',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q5',
        question: 'What is database "indexing" primarily used to improve?',
        options: [
          'Read/query performance for specific lookups',
          'Write-only performance always',
          'Security only',
          'Backup speed only',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q6',
        question: 'What is a "transaction" in a database?',
        options: [
          'A group of operations executed as a single all-or-nothing unit',
          'A single SQL keyword',
          'A network request',
          'A billing event',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q7',
        question: 'What does ACID stand for in the context of database transactions?',
        options: [
          'Atomicity, Consistency, Isolation, Durability',
          'Access, Control, Identity, Data',
          'Always Consistent In Database',
          'Application Compute Infrastructure Design',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q8',
        question: 'What is denormalization sometimes used for in NoSQL data modeling?',
        options: [
          'Duplicating data to optimize for read performance and access patterns',
          'Removing all duplicate data always',
          'Encrypting the database',
          'Reducing storage to zero',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q9',
        question: 'What is a "partition key" used for in DynamoDB?',
        options: [
          'Determining how data is distributed across storage partitions',
          'Formatting the UI',
          'Managing IAM roles',
          'Compiling queries',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-databases-q10',
        question: 'When would you choose a relational database over a NoSQL database?',
        options: [
          'When you need complex multi-table joins and strong transactional guarantees',
          'When you need unlimited horizontal scale with no schema',
          'When you never need to query relationships',
          'When you have no structured data at all',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-packaging': {
    skillId: 'pd-packaging',
    questions: [
      {
        id: 'pd-packaging-q1',
        question: 'What is the purpose of a Python virtual environment?',
        options: [
          'To isolate project dependencies from the system Python and other projects',
          'To speed up the CPU',
          'To encrypt your source code',
          'To replace Git',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q2',
        question: "Which file commonly lists a Python project's dependencies?",
        options: ['requirements.txt', 'index.html', 'Dockerfile only', 'README.md'],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q3',
        question: 'What command typically creates a virtual environment in Python?',
        options: ['python -m venv env', 'pip freeze', 'python -m pip install', 'git init'],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q4',
        question: 'What does `pip install -r requirements.txt` do?',
        options: [
          'Installs all dependencies listed in the file',
          'Deletes installed packages',
          'Creates a new virtual environment',
          'Runs the test suite',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q5',
        question: 'What is the purpose of `pyproject.toml` in modern Python packaging?',
        options: [
          'Declaring build system and project metadata/dependencies',
          'Storing runtime logs',
          'Configuring a web server',
          'Managing IAM roles',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q6',
        question: 'Why pin dependency versions in a requirements file?',
        options: [
          'To ensure reproducible builds across environments',
          'To make installs slower',
          'It is required by Python syntax',
          'To prevent any updates ever',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q7',
        question: 'What is "semantic versioning" (e.g., 1.2.3)?',
        options: [
          'A convention where version numbers indicate major/minor/patch changes',
          'A random numbering scheme',
          'A security certificate',
          'A database version',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q8',
        question: 'What is the purpose of packaging a Python project (e.g., building a wheel)?',
        options: [
          'To distribute the code in an installable, reusable format',
          'To delete unused code',
          'To compile it into machine code',
          'To encrypt source files',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q9',
        question: 'What problem do virtual environments solve?',
        options: [
          'Conflicting dependency versions between different projects',
          'Slow internet connections',
          'Missing hardware drivers',
          'Firewall rules',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-packaging-q10',
        question: 'What is a common tool for managing Python dependencies and virtual environments together?',
        options: ['Poetry', 'chmod', 'grep', 'cron'],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-git': {
    skillId: 'pd-git',
    questions: [
      {
        id: 'pd-git-q1',
        question: 'What command creates a new branch and switches to it in one step?',
        options: ['git commit -b', 'git checkout -b <branch-name>', 'git merge -b', 'git clone -b'],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-git-q2',
        question: 'What is the purpose of a pull request?',
        options: [
          'To permanently delete a branch',
          'To propose and review code changes before merging',
          'To directly push to production',
          'To compile the code',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-git-q3',
        question: 'What does `git clone` do?',
        options: [
          'Copies a remote repository to your local machine',
          'Deletes a branch',
          'Merges two branches',
          'Pushes local changes',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q4',
        question: 'What is the purpose of `git commit`?',
        options: [
          'Recording a snapshot of staged changes with a message',
          'Deleting the repository',
          'Creating a new remote',
          'Downloading changes',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q5',
        question: 'What does `git merge` do?',
        options: [
          'Combines changes from one branch into another',
          'Deletes uncommitted changes',
          'Creates a new repository',
          'Renames a branch',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q6',
        question: 'What is a "merge conflict"?',
        options: [
          "When Git can't automatically reconcile differing changes to the same lines",
          'A network error',
          'A missing commit message',
          'A type of branch',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q7',
        question: 'What does `git status` show?',
        options: [
          'The state of the working directory and staging area',
          'The commit history graph',
          'The remote URL only',
          'The list of branches only',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q8',
        question: 'What is the purpose of a `.gitignore` file?',
        options: [
          "Specifying files/folders Git should not track",
          'Deleting tracked files',
          'Encrypting the repository',
          'Listing collaborators',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q9',
        question: 'What does `git rebase` do differently from `git merge`?',
        options: [
          'Reapplies commits on top of another base, creating a linear history',
          'Deletes all commit history',
          'Only works on remote branches',
          'Automatically resolves all conflicts',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-git-q10',
        question: 'Why review a diff before committing?',
        options: [
          'To verify exactly what changes will be recorded',
          'It is not useful',
          'To slow down development',
          'To bypass testing',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
  'pd-async': {
    skillId: 'pd-async',
    questions: [
      {
        id: 'pd-async-q1',
        question: 'What keyword pair is used in Python to define and await asynchronous functions?',
        options: ['async / await', 'try / except', 'yield / return', 'class / def'],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q2',
        question: 'What kind of workload benefits most from asynchronous programming?',
        options: [
          'CPU-bound number crunching with no I/O',
          'I/O-bound tasks like network requests where the program can wait efficiently',
          'Static HTML rendering only',
          'Compiling C++ code',
        ],
        correctOptionIndex: 1,
      },
      {
        id: 'pd-async-q3',
        question: 'What is an "event loop" in asynchronous programming?',
        options: [
          'The mechanism that schedules and runs asynchronous tasks',
          'A type of database',
          'A network protocol',
          'A CSS layout',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q4',
        question: 'What happens when you `await` a coroutine in Python?',
        options: [
          'Execution pauses there and yields control until the awaited task completes',
          'The program crashes',
          'It runs synchronously, blocking everything',
          'It cancels the task immediately',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q5',
        question: 'What is a common pitfall of mixing blocking (synchronous) calls inside async code?',
        options: [
          'It can block the entire event loop and hurt concurrency',
          'It always speeds things up',
          'It has no effect',
          'It automatically becomes async',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q6',
        question: 'What Python library is commonly used for making asynchronous HTTP requests?',
        options: ['httpx or aiohttp', 'os', 'json only', 're'],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q7',
        question: 'What does `asyncio.gather()` do?',
        options: [
          'Runs multiple coroutines concurrently and waits for all to complete',
          'Deletes running tasks',
          'Blocks all other code',
          'Only runs one task at a time',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q8',
        question: 'Why might async programming NOT help a CPU-bound task like heavy number crunching?',
        options: [
          'Because the bottleneck is CPU time, not waiting on I/O',
          'Because async always makes CPU tasks faster',
          "Because CPU-bound tasks can't run in Python at all",
          'Because async removes the need for CPU entirely',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q9',
        question: 'What is a "task" in asyncio?',
        options: [
          'A wrapper that schedules a coroutine to run concurrently on the event loop',
          'A database record',
          'A Docker container',
          'A Git branch',
        ],
        correctOptionIndex: 0,
      },
      {
        id: 'pd-async-q10',
        question: "What's a benefit of async web servers for I/O-heavy APIs?",
        options: [
          'They can handle many concurrent connections efficiently while waiting on I/O',
          'They use more threads than processes always',
          'They eliminate the need for a database',
          'They only work with one user at a time',
        ],
        correctOptionIndex: 0,
      },
    ],
  },
};

export function getQuizForSkill(skillId: string): SkillQuiz | undefined {
  return SKILL_QUIZZES[skillId];
}
